### ISSUE TITLE
Node will be drained after manually uncordoned

### ISSUE THREAD

**Issue by openstacker** [planetlabs/draino#17]
Hi @negz, now OpenStack Magnum (a managed k8s service like GKE) team is trying to adopt draino and we're doing some testing now. There is one case I'd like to confirm with you.

By default, after a node is cordoned, draino will wait 10 mins before draining it. But in my testing, even if the node is uncordoned by the cluster admin, draino will still drain it. Is it working as designed? Thank you for any comments. Cheers.

**Comment by negz** [comment]
I'm glad Magnum is interested in trying Draino!

There's not currently a causal relationship between Draino's cordon and drain events. When we see an eligible node (one with all of the configured labels and any of the configured conditions) said node is immediately cordoned and a drain is [queued via `time.After()`]( https://github.com/planetlabs/draino/blob/master/internal/kubernetes/eventhandler.go#L121). The goal of this process is to space out drains and thus minimise potential service disruption; i.e. if we discover three eligible nodes at time N, assuming drain buffer time B, the drains would be scheduled for N, N+B, and N+B*2.

Could you provide a little context around your use case here? There's not currently any way to prevent Draino processing an eligible node. We could add logic to abort the scheduled drain if the node had been uncordoned, but Draino would simply re-cordon it and schedule a new Drain next time its watch on the API server was refreshed.

**Comment by negz** [comment]
> I think it would be nice if there is a chance that cluster admin can interrupt the cordon/drain process because the admin/operator knows better from the overall cluster view.

There's a few things we could do here.

### Abort if an eligible node is uncordoned
In this case we'd have Draino abort a drain if the node was no longer cordoned at the scheduled drain time. However, Draino works by watching the Kubernetes API for eligible nodes. The watch resyncs every 30 minutes, i.e. every 30 minutes Draino reprocesses all eligible nodes. This could result in a scenario like:
1. Draino detects an eligible node, cordons it, and schedules it to be drained in 10 minutes.
1. The cluster operator notices this and uncordons the node.
1. The 10 minute timer expires, Draino notices the node is no longer cordoned, and aborts the drain.
1. A watch resync occurs, the node is still eligible because its node conditions and labels have not changed, so Draino cordons it again and schedules a new drain.

The other consideration here is that Draino doesn't buffer the _first_ drain. Assume Draino is configured with a 10 minute drain buffer, and has not drained any nodes in the last 10 minutes. If Draino observes a eligible node it will drain it immediately, because waiting 10 minutes before draining it would not be any less disruptive to the cluster. For most clusters this will be the most common case, i.e. one node will break every now and then and be immediately cordoned and drained without giving the cluster operator time to abort anything.

### Abort if a node annotation is present
We could address the resync issue mentioned above by using a node annotation like `draino.kubernetes.io/ignore-node: true` to exclude nodes from processing. Draino already supports chained filters to limit which nodes are eligible for processing. If we filtered out nodes _and_ aborted scheduled drains when we saw this annotation we could allow cluster operators to both abort a scheduled drain and ensure the node was not processed again in future. Keep in mind this method still doesn't address the fact that Draino will drain nodes immediately if no drains have happened recently, and thus the operator wouldn't usually get a chance to abort drains.

### Don't change anything
The node problem detector only sets node conditions for _permanent_ node issues, so hypothetically if one of Draino's node conditions have been set there's nothing the cluster operator can actually do to fix the node. With this in mind I can only think of two use cases here:

* The node is running some pods that you don't want to be drained. If this is the case, then why let the node be eligible for Draino processing in the first place? Use node labels to ensure nodes running critical pods aren't considered eligible by Draino.
* The cluster operator wants to do some triage on the node when it's determined to be broken. This is still possible if Draino drains the node. The node will be drained, but will still be up and running for the operator to poke at and figure out what happened.

**Comment by openstacker** [comment]
Thank you for the very good detailed explanation. As for the NPD part, based on my understanding, even if there is no NPD, draino can still work well with those k8s built-in node conditions, right? And the cases we need NPD are the scenarios that user would like to support more customized conditions. Am I understanding the relationship between NPD and Draino correctly? Thanks.

**Comment by openstacker** [comment]
Thank you, that makes sense. BTW, are you using [Autoscaler](https://github.com/kubernetes/autoscaler) to do the node replacement after the node being drained? Or any other tool you would recommend? Cheers.

**Comment by negz** [comment]
That's right, we use the cluster autoscaler to handle the node replacement. It will add a new node if the drained pods don't fit on other existing nodes, and will also remove the drained node due to underutilisation.

**Comment by negz** [comment]
I'm going to close this issue as I believe your questions are answered. Please feel free to reopen if that's not the case!
