### ISSUE TITLE
drain all nodes if no labels specified

### ISSUE THREAD

**Issue by maxormo** [planetlabs/draino#29]
is it intended behavior? I think that this is error prone default that is better to change to the opposite= no nodes cordoned if labels are not specified.
As for the desire to drain all nodes no matter what extra flag can be added like --drain-all

**Comment by jacobstr** [comment]
This does feel dangerous. It's not a terrible if you at least still have node conditions, but it would be quite pathological if draino shot all your nodes if you misconfigured it:
- without any labels
- without any conditions

We're using the label functionality to restrict draino to only draino worker nodes in our cluster. Meanwhile, we don't autoscale control nodes so if draino did decide to kill one we wouldn't see the autoremediation effects.

I'm receptive to further discussion here!

**Comment by maxormo** [comment]
this is what happened when i was experimenting on dev cluster, I accidentally removed dry run and haven't had any labels and conditions. So next thing I saw that I have all nodes cordoned

**Comment by negz** [comment]
This is not intended behaviour - it was my intention that you must specify at least one _node condition_ in order to start Draino. I've submitted #31, which will make Draino refuse to start if you don't explicitly tell it which node conditions must exist in order for a node to be a candidate for cordoning and draining.
